version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
    cooldown:
      default-days: 1
      exclude:
        - "Microsoft.*"
        - "System.CommandLine"
    groups:
      microsoft:
        patterns:
          - "Microsoft.Extensions.*"
      ffmpeg:
        patterns:
          - "FFMpegCore"
          - "FFMpegCore.*"
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "21:00"
      timezone: "Europe/Helsinki"
