<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Content Include="..\Testvideos\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Testvideos\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)\..\..\ffmpeg\**\*" CopyToOutputDirectory="PreserveNewest" Link="ffmpeg\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
