<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\FFmpegConverter\FFmpegConverter.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\Testvideos\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Testvideos\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
</Project>
