<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VideoConverter</RootNamespace>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x64;linux-x64;</RuntimeIdentifiers>
    <PlatformTarget>anycpu</PlatformTarget>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishDir>..\..\publish</PublishDir>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FFmpegConverter\FFmpegConverter.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <Content Include="config.json" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
