name: release
on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "**.props"
      - "global.json"
      - ".github/workflows/release.yml"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "**.props"
      - "global.json"
      - ".github/workflows/release.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup .NET
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
        with:
          global-json-file: ./global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $RID = "win-x64"
          $OUT = "video-converter-$RID.zip"
          $PUBLISH_DIR = "publish/$RID"
          dotnet publish src/VideoConverter -c Release -r $RID -o $PUBLISH_DIR
          dotnet publish src/FFmpegDownloader -c Release -r $RID -o $PUBLISH_DIR
          Compress-Archive -Path "$PUBLISH_DIR\*" -DestinationPath $OUT -Force
          echo "PACKAGE_PATH=$OUT" >> $env:GITHUB_ENV
      - name: Publish Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          RID=linux-x64
          OUT=video-converter-$RID.tar.gz
          PUBLISH_DIR=publish/$RID
          dotnet publish src/VideoConverter -c Release -r $RID -o $PUBLISH_DIR
          dotnet publish src/FFmpegDownloader -c Release -r $RID -o $PUBLISH_DIR
          tar -czvf $OUT -C $PUBLISH_DIR .
          echo "PACKAGE_PATH=$OUT" >> $GITHUB_ENV
      - name: Upload artifacts
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ matrix.os }}
          path: ${{ env.PACKAGE_PATH }}
          overwrite: true
          retention-days: 1
          if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: build
    env:
      TAG: v1.0.0
      TITLE: Video Converter
      NOTES: Download latest version
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Download artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: ./packages
          merge-multiple: true
      - name: Create release
        shell: bash
        run: |
          gh release delete "$TAG" --yes --cleanup-tag || true
          gh release create "$TAG" --latest --title "$TITLE" --notes "$NOTES"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload packages
        shell: bash
        run: |
          for f in ./packages/*; do
            gh release upload "$TAG" "$f" --clobber
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
