name: test
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.props"
      - "global.json"
      - ".github/workflows/test.yml"
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          global-json-file: ./global.json
      - name: Test
        run: dotnet test --project tests/UnitTests -c Release
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          global-json-file: ./global.json
      - name: Download FFmpeg binaries
        run: dotnet run --project src/FFmpegDownloader -c Release ${{ github.workspace }}/ffmpeg
      - name: Test
        run: dotnet test --project tests/IntegrationTests -c Release
        env:
          FFMPEG_PATH: ${{ github.workspace }}/ffmpeg
  e2e-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          global-json-file: ./global.json
      - name: Download FFmpeg binaries
        run: dotnet run --project src/FFmpegDownloader -c Release ${{ github.workspace }}/ffmpeg
      - name: Test
        run: dotnet test --project tests/E2ETests -c Release
        env:
          FFMPEG_PATH: ${{ github.workspace }}/ffmpeg
          TESTFILE_URL: ${{ vars.TESTFILE_URL }}
